apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: azure-vote-front 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-vote-front 
    spec:
      containers:
        - name: azure-vote-front 
          image: acrdefault.azurecr.io/azure-vote-front 
          ports:
          - containerPort: 8080:80